FROM golang:1.17 as build

ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /build-app

ENV TZ 'Asia/Tehran'

ADD go.mod go.sum /build-app/
RUN go mod download
COPY . .
RUN make service

