// Code generated by sqlc. DO NOT EDIT.

package savedmessages

import (
	"database/sql"
	"time"
)

type SavedMessage struct {
	ID           int32
	Message      sql.NullString
	IngAccountID int32
	WriterID     int32
	CreateTime   time.Time
	UpdateTime   time.Time
}
