// Code generated by sqlc. DO NOT EDIT.

package organization

import (
	"time"
)

type Organization struct {
	ID         int32
	Name       string
	OwnerID    int32
	CreateTime time.Time
	UpdateTime time.Time
}
