// Code generated by sqlc. DO NOT EDIT.

package organization

import (
	"context"
)

type Querier interface {
	AddOrganization(ctx context.Context, arg AddOrganizationParams) (Organization, error)
	DeleteOrganization(ctx context.Context, id int32) (Organization, error)
	GetOrganization(ctx context.Context, id int32) (Organization, error)
	GetOrganizationByOwnerID(ctx context.Context, ownerID int32) ([]Organization, error)
	GetOrganizations(ctx context.Context) ([]Organization, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
}

var _ Querier = (*Queries)(nil)
