// Code generated by sqlc. DO NOT EDIT.

package roles

import (
	"time"
)

type Role struct {
	ID             int32
	OrganizationID int32
	CreatorID      int32
	RoleType       int32
	CreateTime     time.Time
	UpdateTime     time.Time
}
