// Code generated by sqlc. DO NOT EDIT.

package roles

import (
	"context"
)

type Querier interface {
	AddRole(ctx context.Context, arg AddRoleParams) (Role, error)
	DeleteRole(ctx context.Context, id int32) (Role, error)
	GetRole(ctx context.Context, id int32) (Role, error)
	GetRoleByCreatorID(ctx context.Context, creatorID int32) ([]Role, error)
	GetRoleByOrganizationID(ctx context.Context, organizationID int32) ([]Role, error)
	GetRoleByOrganizationIDAndRoleType(ctx context.Context, arg GetRoleByOrganizationIDAndRoleTypeParams) (Role, error)
	GetRoles(ctx context.Context) ([]Role, error)
}

var _ Querier = (*Queries)(nil)
