package main

import (
	"fmt"
	"net"
	"os"

	"git.cafebazaar.ir/divar/autogenerated/divar_interface.git/divar_cloud_sand_boxing"
	"git.cafebazaar.ir/divar/autogenerated/divar_rpc.git/server"
	"git.cafebazaar.ir/divar/cloud-sand-boxing/internal/config"
	grpcAPI "git.cafebazaar.ir/divar/cloud-sand-boxing/internal/core/grpc"
	"git.cafebazaar.ir/divar/cloud-sand-boxing/pkg/logger"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
)

const serviceName = "divar_cloud_sand_boxing"

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
}

func loadConfigOrPanic(cmd *cobra.Command) *config.Config {
	conf, err := config.LoadConfig(cmd)
	if err != nil {
		logrus.WithError(err).Panic("Failed to load configurations")
	}
	return conf
}

func configureLoggerOrPanic(loggerConfig logger.Config) {
	if err := logger.Initialize(&loggerConfig); err != nil {
		logrus.WithError(err).Panic("Failed to configure logger")
	}
}

func getGrpcServer(grpcServicer *grpcAPI.ServiceImplementation,
	interceptors []grpc.UnaryServerInterceptor) *grpc.Server {

	baseServer := server.NewGrpc(serviceName, server.WithInterceptor(interceptors...))
	divar_cloud_sand_boxing.RegisterDivarCloudSandBoxingServer(baseServer, grpcServicer)
	reflection.Register(baseServer)

	return baseServer
}

func startGrpcServerOrPanic(listenPort int, grpcServer *grpc.Server) {
	grpcAddr := fmt.Sprintf(":%d", listenPort)
	grpcListener, err := net.Listen("tcp", grpcAddr)
	if err != nil {
		logrus.WithError(err).Panic("Failed to listen")
		return
	}

	err = grpcServer.Serve(grpcListener)
	if err != nil {
		logrus.WithError(err).Panic("Failed to serve")
	}
}
