// Code generated by sqlc. DO NOT EDIT.

package ingpages

import (
	"time"
)

type IngPage struct {
	ID             int32
	Name           string
	Token          string
	OrganizationID int32
	CreatorID      int32
	CreateTime     time.Time
	UpdateTime     time.Time
}
