// Code generated by sqlc. DO NOT EDIT.

package ingpages

import (
	"context"
)

type Querier interface {
	AddIngPage(ctx context.Context, arg AddIngPageParams) (IngPage, error)
	DeleteIngPage(ctx context.Context, id int32) (IngPage, error)
	GetIngPage(ctx context.Context, id int32) (IngPage, error)
	GetIngPageByOrganizationID(ctx context.Context, organizationID int32) ([]IngPage, error)
	GetIngPageByUserID(ctx context.Context, creatorID int32) ([]IngPage, error)
	GetIngPages(ctx context.Context) ([]IngPage, error)
	UpdateIngPageToken(ctx context.Context, arg UpdateIngPageTokenParams) (IngPage, error)
}

var _ Querier = (*Queries)(nil)
