package rest

import "github.com/gin-gonic/gin"

// frequent message is not just saved messages. For example, it can be generated by AI too.

func (s *Server) SaveMessage(c *gin.Context) {
	//s.frequentMessagesService.Add()
}

func (s *Server) GetSavedMessages(c *gin.Context) {
	//s.frequentMessagesService.GetSavedMessages()
}

func (s *Server) DeleteSavedMessage(c *gin.Context) {
	//s.frequentMessagesService.Delete()
}

func (s *Server) UpdateSavedMessage(c *gin.Context) {
	//s.frequentMessagesService.UpdateSavedMessageMessage()
}
