// Code generated by sqlc. DO NOT EDIT.

package access

import (
	"time"
)

type Access struct {
	ID             int32
	OrganizationID int32
	UserID         int32
	RoleID         int32
	CreateTime     time.Time
	UpdateTime     time.Time
}
