// Code generated by sqlc. DO NOT EDIT.

package users

import (
	"time"
)

type User struct {
	ID         int32
	Name       string
	Username   string
	Email      string
	Phone      string
	Password   string
	CreateTime time.Time
	UpdateTime time.Time
}
