// Code generated by sqlc. DO NOT EDIT.

package users

import (
	"context"
)

type Querier interface {
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) (User, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByUserName(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
