// Code generated by sqlc. DO NOT EDIT.

package ingaccounts

import (
	"database/sql"
	"time"
)

type IngAccount struct {
	ID         int32
	Name       string
	Token      sql.NullString
	UserID     int32
	CreateTime time.Time
	UpdateTime time.Time
}
