// Code generated by sqlc. DO NOT EDIT.

package ingaccounts

import (
	"context"
)

type Querier interface {
	AddIngAccount(ctx context.Context, arg AddIngAccountParams) (IngAccount, error)
	DeleteIngAccount(ctx context.Context, id int32) (IngAccount, error)
	GetIngAccount(ctx context.Context, id int32) (IngAccount, error)
	GetIngAccountByUserID(ctx context.Context, userID int32) (IngAccount, error)
	GetIngAccounts(ctx context.Context) ([]IngAccount, error)
	UpdateIngAccountToken(ctx context.Context, arg UpdateIngAccountTokenParams) (IngAccount, error)
}

var _ Querier = (*Queries)(nil)
